<?php

// autoload.php generated by Composer

class AutoLoader {
  private static $loader;

  public static function loadClassLoader( $class ) {

    if ( 'Composer\Autoload\ClassLoader' === $class ) {
      require __DIR__ . '/controllers/loader.php';
    }

  }

  public static function getLoader() {

    if ( null !== self::$loader ) {
      return self::$loader;
    }

    $vendorDir = dirname( dirname( __FILE__ ) ) . '/core/vendor';
    $baseDir = dirname( $vendorDir );

    spl_autoload_register( array( 'AutoLoader', 'loadClassLoader' ), true, true );
    self::$loader = $loader = new \Composer\Autoload\ClassLoader();
    spl_autoload_unregister( array( 'AutoLoader', 'loadClassLoader' ) );

    // Load libraries that use namespaces.
    foreach ( array( 'Flawless\\' => array( $baseDir . '/controllers' ), 'UsabilityDynamics\\' => array( $vendorDir ) ) as $namespace => $path ) {
      $loader->set( $namespace, $path );
    }

    // Loads libraries that do not use namespaces.
    $loader->addClassMap( array(
      'QRcode' => $vendorDir . '/tecnick.com/tcpdf/include/barcodes/qrcode.php',
      'TCPDF' => $vendorDir . '/tecnick.com/tcpdf/tcpdf.php'
    ));

    $loader->register( true );

    return $loader;
  }
}

return AutoLoader::getLoader();
