<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    $vendorDir . '/rhumsaa/array_column/src/array_column.php',
    $vendorDir . '/wp-cli/php-cli-tools/lib/cli/cli.php',
    $vendorDir . '/wp-cli/wp-cli/php/Spyc.php',
);
