<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'EDM\\Application\\Bootstrap' => $baseDir . '/wp-content/mu-plugins/lib/class-bootstrap.php',
    'EDM\\Application\\Migration' => $baseDir . '/wp-content/mu-plugins/lib/class-migrate.php',
);
